### ISSUE TITLE
The number of val-shot choice.

### ISSUE THREAD

**Issue by FrigEgg** [kjunelee/MetaOptNet#17]
Some as before. Thanks for your code! I think it is really great work.
The test epoch is chosen based on the accuracy on val set, right? I want to ask. If we need to use the 5-shot val to choose the model for the 5-shot test and the 1-shot val to choose the model for the 1-shot test. Or just use the 5-shot val to choose the model for both the 5-shot and 1-shot test.

I want to ask this because when I use 5-shot val to choose model for 1-shot test, I all-way cannot get the accuracy in your paper.

**Comment by kjunelee** [comment]
Just use the 5-shot val to choose the model for both the 5-shot and 1-shot test.
=> This is the option I chose.

In practice, meta-training has some degree of variance in the final performance due to factors like different random seeds in different versions of packages. For example, I used Python 2 for the submission, but when I tried Python 3 after the submission the performance slightly went down.

**Comment by FrigEgg** [comment]
I do use python3. Thank for your help!
