### ISSUE TITLE
Why the accuracy of the Prototypical Network is higher than the reported version in paper?

### ISSUE THREAD

**Issue by WHQ1111** [kjunelee/MetaOptNet#42]
When I use your prototypical network to perform miniImageNet classification, the accuracy obtained is higher than that reported in the paper? Specifically, I use 

> python train.py --gpu 0 --save_path 'Logs/miniImageNet_Proto_5w_1s' --train_way 5 --val_way 5 --train_shot 1 --val_shot 1 --train_query 6 --val_query 15 --head ProtoNet --network ProtoNet --dataset miniImageNet

The accuracy I get is 52.47 ± 0.67, which is higher than the 49.42 ± 0.78 reported in the paper。
Then I use 

> python train.py --gpu 0 --save_path 'Logs/miniImageNet_Proto_5w_5s' --train_way 5 --val_way 5 --train_shot 5 --val_shot 5 --train_query 6 --val_query 15 --head ProtoNet --network ProtoNet --dataset miniImageNet

The accuracy I get is 70.65±0.52, which is higher than the 68.20±0.66 reported in the paper。
Could you explain the reason?Is it related to data reading, or is it due to some standardization techniques?

**Comment by kjunelee** [comment]
The result of 49.42 ± 0.78 % is the one reported in original paper of the Prototypical Networks by Snell et al. In this result, a lot of regularization techniques were not used.
As shown in Table 4 of our paper, various regularization methods can improve the performance by a significant margin. Also I have discovered data loader also contributes to some degree. I think it is due to difference in shuffling mechanism. So it is a combination of regularization and data loader that improved the result of Prototypical Networks (and this result is shown in Table 3 of our paper).
